### ISSUE TITLE
PDF For sgj

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#245] opened 2015-09-17 19:24 UTC
The PDF for sgj is not building, error is:
`tex error       > error on line 420 in file /tmp/obs_build_pdf.4efTiw/obs-sgj-v4_1.tex: ! Argument of \next has an extra }`

**Comment by alerque** [comment] 2015-09-17 19:28
That looks like you have garbage in the input somewhere, either an opening or a closing curly brace. If a brace is required in the output it needs to be escaped and the way some of the OBS text is passed through into the template it isn't looking for that sort of problem. But the problem is not likely to be in the template or the scripting because it would show up in the other languages if it was.

**Comment by jag3773** [comment] 2015-09-17 19:48
TeX file and log attached.

[obs-sgj-v4_1.log | uploaded via ZenHub](https://files.zenhub.io/55fb18ae3c7c7300306575bc)

[obs-sgj-v4_1.tex | uploaded via ZenHub](https://files.zenhub.io/55fb18ce3c7c7300306575bd)

**Comment by alerque** [comment] 2015-09-21 17:18
I'm unable to verify or debug this right now because the API isn't returning some of the data for this language so the retrieval processes bombs before it it even gets to processing the results. In particular the [obs-sgi-front-matter.json](https://api.unfoldingword.org/obs/txt/1/sgi/obs-sgi-front-matter.json) file needs to return something other than a 404 (and the same for the other fragments).

Where were you building this that short circuited the normal workflow?

**Comment by jag3773** [comment] 2015-09-21 17:53
That link you have above should point at https://api.unfoldingword.org/obs/txt/1/sgj/obs-sgj-front-matter.json -- note sgj not sgi.

**Comment by alerque** [comment] 2015-09-21 17:55
Oh. Doh. That might explain why I was having difficulty.

**Comment by alerque** [comment] 2015-09-23 06:19
This error is primarily caused by a faux pas in the Surgujia data set. Additionally there are some broken RegExes in the the export script which I will send along a fix for, but correcting the Surgujia issue should fix this error.

I will also include a fix for the font stack in a PR as ever when the data is fixed the PDF will currently still come out garbled, but fixing the data is step 1. I have submitted a PR over on Door43/d43-sgj#1. If there is a better way to submit scripted changes to the data sets please let me know what that is.

**Closed as completed** 2015-09-24 20:44 UTC
Labels: bug
